# Generated by Django 5.2.4 on 2025-08-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrcet', '0003_student_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csd',
        ),
    ]
